[models.lv_chordia]
description = "ISMIR 2019 five-model chord recognition ensemble"
license = "MIT"
provenance = "https://github.com/music-x-lab/ISMIR2019-Large-Vocabulary-Chord-Recognition"
source_revision = "master"
updated_at = "2026-07-15"

[[models.lv_chordia.artifacts]]
name = "joint_chord_net_ismir_naive_v1.0_reweight(0.0,10.0)_s0.best.sdict"
url = "package://lv_chordia/cache_data/joint_chord_net_ismir_naive_v1.0_reweight(0.0,10.0)_s0.best.sdict"
sha256 = "921b42d5d1cf9ce1c0c0e45a74d409b8066e0acec46058ef74e24ee0fb540761"

[[models.lv_chordia.artifacts]]
name = "joint_chord_net_ismir_naive_v1.0_reweight(0.0,10.0)_s1.best.sdict"
url = "package://lv_chordia/cache_data/joint_chord_net_ismir_naive_v1.0_reweight(0.0,10.0)_s1.best.sdict"
sha256 = "bcb75859e0efa256696cf5da396b320093317b9b1d9560c304f46c25fe1f8b17"

[[models.lv_chordia.artifacts]]
name = "joint_chord_net_ismir_naive_v1.0_reweight(0.0,10.0)_s2.best.sdict"
url = "package://lv_chordia/cache_data/joint_chord_net_ismir_naive_v1.0_reweight(0.0,10.0)_s2.best.sdict"
sha256 = "acddf85c3fff29954c4877021177d72e2cba9f729ce80c1010f054c477bf3f61"

[[models.lv_chordia.artifacts]]
name = "joint_chord_net_ismir_naive_v1.0_reweight(0.0,10.0)_s3.best.sdict"
url = "package://lv_chordia/cache_data/joint_chord_net_ismir_naive_v1.0_reweight(0.0,10.0)_s3.best.sdict"
sha256 = "65d81a3ab73435aaaade586981b4cabdf57b8953d76052703e6968c32ef8421c"

[[models.lv_chordia.artifacts]]
name = "joint_chord_net_ismir_naive_v1.0_reweight(0.0,10.0)_s4.best.sdict"
url = "package://lv_chordia/cache_data/joint_chord_net_ismir_naive_v1.0_reweight(0.0,10.0)_s4.best.sdict"
sha256 = "5ff6b0ec85640e17a09a9b3de68c93fdd45adc24488e8fa9be5715c28d561122"
